Update base to 202.15
Signed-off-by: Lugang He <helugang@uniontech.com>

diff --git a/debian/scripts/close-release b/debian/scripts/close-release
--- a/debian/scripts/close-release
+++ b/debian/scripts/close-release
@@ -3,12 +3,69 @@
 # Close a release
 #
 
+function usage()
+{
+	cat <<EOF
+Usage: $(basename "${0}") [-h] [-s SUFFIX]
+
+Close a release, i.e., create a release commit.
+
+Optional arguments:
+  -h, --help           Show this help text and exit.
+  -s, --suffix SUFFIX  Generate the new package version by appending SUFFIX to
+                       the current version rather than incrementing the upload
+                       number by one.
+EOF
+}
+
+suffix=
+
+while [ ${#} -gt 0 ] ; do
+	case "${1}" in
+		-h|--help)
+			usage
+			exit
+			;;
+		-s|--suffix)
+			shift
+			suffix=${1}
+			;;
+		*)
+			echo "Invalid argument: ${1}" >&2
+			exit 2
+			;;
+	esac
+	shift
+done
+
+# Current upstream commit and version
+. debian/upstream
+
+# Current package release and version
 release=$(dpkg-parsechangelog -SDistribution)
 version=$(dpkg-parsechangelog -SVersion)
 
-# The version and tag of the new release
-new_version="${version%.*}.$((${version##*.} + 1))"
+# New release version and tag
+if [ "${version%-*}" = "${VERSION}" ] ; then
+	if [ -n "${suffix}" ] ; then
+		# Append the provided suffix
+		new_version=${version}${suffix}
+	else
+		# Bump the upload number
+		upload=$(echo "${version}" | grep -o '[0-9]*$')
+		new_version=${version%"${upload}"}$((upload + 1))
+	fi
+else
+	# New upstream version
+	new_version="${VERSION}-0ubuntu1"
+
+	if [ -n "${suffix}" ] ; then
+		# Append the provided suffix
+		new_version=${version}${suffix}
+	fi
+fi
 new_tag="Ubuntu-${new_version}"
+new_tag=${new_tag//\~/_}
 
 # Check if the tag exists already
 if git rev-parse "${new_tag}" >/dev/null 2>&1 ; then
@@ -16,8 +73,8 @@ if git rev-parse "${new_tag}" >/dev/null 2>&1 ; then
 	exit 1
 fi
 
-# Find the previous release commit
-prev_subject="UBUNTU: Ubuntu-${version}"
+# Find the previous release commit (skip dummy versions ending in .0)
+prev_subject="UBUNTU: Ubuntu-${version%.0}"
 prev_commit=$(git log --format='%H %s' | \
 				  grep -m1 -P "^[0-9a-f]{40} ${prev_subject}$" || true)
 prev_commit=${prev_commit%% *}
@@ -31,22 +88,7 @@ fi
 {
 	echo "linux-firmware (${new_version}) ${release}; urgency=medium"
 	echo
-
-	while IFS= read -r line ; do
-		commit=${line%% *}
-		subject=${line#* }
-		# shellcheck disable=SC2001
-		subject=$(echo "${subject}" | sed 's,\s*UBUNTU:\s*,,')
-
-		echo "  * ${subject}"
-
-		# For rebase commits, add the list of changes from the commit message
-		if [ "${subject#Rebase to upstream commit}" != "${subject}" ] ; then
-			git log --format=%b "${commit}" -1 | grep -P '^Rebase|^- ' | \
-				sed -e 's,^,    ,'
-		fi
-	done < <(git log --reverse --format='%h %s' "${prev_commit}"..)
-
+	debian/scripts/generate-changelog "${prev_commit}"..
 	echo
 	echo " -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)"
 	echo
@@ -54,6 +96,6 @@ fi
 } > debian/changelog.new
 mv debian/changelog.new debian/changelog
 
-# Commit and tag the new release
-git commit -s -m "UBUNTU: ${new_tag}" -- debian/changelog
-git tag -s -m  "UBUNTU: ${new_tag}" "${new_tag}"
+# Commit the new release
+git commit -s -m "UBUNTU: Ubuntu-${new_version}" -- debian/changelog
+debian/scripts/tag-release
diff --git a/debian/scripts/rebase-upstream b/debian/scripts/rebase-upstream
--- a/debian/scripts/rebase-upstream
+++ b/debian/scripts/rebase-upstream
@@ -9,49 +9,74 @@ function out()
 
 	trap - EXIT INT TERM HUP
 	if [ ${rc} -ne 0 ] ; then
-		echo 'Error: Script failed' >&2
+		echo "Error: Script failed" >&2
 	fi
 
 	exit "${rc}"
 }
 
-trap out EXIT INT TERM HUP
+function usage()
+{
+	cat <<EOF
+Usage: $(basename "${0}") [-h]
 
-# Find the current upstream commit
-if [ -e debian/upstream ] ; then
-	old_base=$(cat debian/upstream)
-else
-	old_base=$(git log --format=%s | grep -m1 -P 'UBUNTU: [Rr]ebase to upstream commit' | sed 's/.* //')
+Rebase onto latest upstream linux-firmware. If not present, adds a new remote
+'upstream', fetches form it, rebases onto upstream/main and adds a rebase
+commit.
+
+Option arguments:
+  -h, --help  Show this help text and exit.
+EOF
+}
+
+while [ ${#} -gt 0 ] ; do
+	case "${1}" in
+		-h|--help)
+			usage
+			exit
+			;;
+		*)
+			echo "Invalid argument: ${1}" >&2
+			exit 2
+			;;
+	esac
+	shift
+done
+
+version=$(dpkg-parsechangelog -SVersion)
+if echo "${version}" | grep -qE '\.[0-9]+$' ; then
+	echo "Current package version (${version}) looks like an SRU version." \
+		 "Not rebasing." >&2
+	exit 1
 fi
+
+trap out EXIT INT TERM HUP
 
 # Add an upstream remote and fetch it
 upstream_git=git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
 if ! git remote | grep -qxF upstream ; then
-    git remote add upstream "${upstream_git}"
+	git remote add upstream "${upstream_git}"
 fi
 git fetch upstream
 
-# Check if a rebase is necessary
-new_base=$(git rev-parse upstream/main)
-if [ "${new_base}" = "${old_base}" ] ; then
-	echo "No rebase necessary"
-	exit
-fi
+# Current upstream commit and version
+. debian/upstream
 
-# Do the rebase
-git rebase "${new_base}"
+# New upstream commit and version
+new_commit=$(git rev-parse upstream/main)
+new_version=$(date --utc +%Y%m%d).git${new_commit::8}
 
-# Add an LP bug reference
-lp=
-if [ -n "${LP:-}" ] ; then
-	lp=" (LP: #${LP})"
-fi
+# Rebase onto upstream/main
+git rebase "${new_commit}"
 
-# Update the upstream hash and commit it
-echo "${new_base}" > debian/upstream
+# Create the rebase commit
+{
+	echo "COMMIT=${new_commit}"
+	echo "VERSION=${new_version}"
+} > debian/upstream
 git add debian/upstream
-git commit -s -m "UBUNTU: Rebase to upstream commit ${new_base}${lp}
+git commit -s -m "UBUNTU: Rebase to upstream commit ${new_commit}
 
 Rebase against ${upstream_git}
-${new_base}
-$(git log --no-merges --reverse --format='- %s' ${old_base}..${new_base})"
+${new_commit}
+$(git log --no-merges --reverse --format='- %s' "${COMMIT}".."${new_commit}")"
